### ISSUE TITLE
making this package case insensitive breaks the Single Responability Principle

### ISSUE THREAD

**Issue by xgbuils** [zeke/similarity#6]
Hi,

People who want to use a case sensitive function should reimplement a new package because this does not allow case sensitive compararisons.

However, if this module was case sensitive, the people who would like a case insensitive version just would need to do:
`similarity(a.toLowerCase(), b.toLowerCase())`.

Cheers!

**Comment by zeke** [comment]
Thanks for the suggestion. What about updating the module to take an "options bag" as a third argument? 

```js
similarity(a, b, {caseSensitive: true})
```
